# Generated by Django 5.2.15 on 2026-07-02 18:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterfallRecoupmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exploitation_field', models.CharField(choices=[('cinema', 'Kino'), ('festivals', 'Festiwale'), ('non_theatrical', 'Non-theatrical / edukacja'), ('linear_tv', 'TV linearna'), ('pay_tv', 'Pay TV'), ('free_tv', 'Free TV'), ('svod', 'SVOD'), ('tvod', 'TVOD'), ('est', 'EST / DTO'), ('avod', 'AVOD'), ('fast', 'FAST'), ('airlines', 'Linie lotnicze'), ('hotels', 'Hotele / hospitality'), ('clips', 'Clips / fragmenty'), ('promo_internet', 'Internet promocyjny'), ('home_video', 'Home video / DVD / Blu-ray'), ('other', 'Inne')], max_length=40, verbose_name='pole eksploatacji')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EUR'), ('USD', 'USD'), ('GBP', 'GBP')], default='PLN', max_length=3, verbose_name='waluta')),
                ('recoupment_pool', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Np. MG, P&A, delivery albo inna kwota odzyskiwana przed splitem.', max_digits=14, verbose_name='pula do recoupmentu')),
                ('distributor_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=5, verbose_name='prowizja dystrybutora %')),
                ('participant_share_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='udzial partnera %')),
                ('include_recoupable_costs', models.BooleanField(default=True, verbose_name='dolicz koszty recoupable z kosztow?')),
                ('fee_after_recoupment', models.BooleanField(default=True, verbose_name='licz fee po recoupment?')),
                ('active', models.BooleanField(default=True, verbose_name='aktywny?')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_rules', to='distribution.title', verbose_name='tytul')),
            ],
            options={
                'verbose_name': 'waterfall / recoupment',
                'verbose_name_plural': 'waterfall / recoupment',
                'ordering': ['title__title_pl', 'exploitation_field'],
                'unique_together': {('title', 'exploitation_field', 'currency')},
            },
        ),
    ]
