# Generated by Django 5.2.15 on 2026-07-02 19:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_cost_applies_to_all_exploitation_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='acquisition_currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta nabycia / MG'),
        ),
        migrations.AddField(
            model_name='title',
            name='mg_advance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='MG / minimum guarantee'),
        ),
        migrations.AlterField(
            model_name='acquisitionagreement',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta'),
        ),
        migrations.AlterField(
            model_name='royaltystatement',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta'),
        ),
        migrations.AlterField(
            model_name='salesagreement',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta'),
        ),
        migrations.AlterField(
            model_name='waterfallrecoupmentrule',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta'),
        ),
    ]
