# Generated by Django 5.2.15 on 2026-07-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_title_acquisition_currency_title_mg_advance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='age_rating',
            field=models.CharField(blank=True, choices=[('all', 'Bez ograniczen'), ('7', '7+'), ('12', '12+'), ('15', '15+'), ('16', '16+'), ('18', '18+')], max_length=20, verbose_name='ograniczenie wiekowe'),
        ),
        migrations.AddField(
            model_name='title',
            name='aspect_ratio',
            field=models.CharField(blank=True, help_text='Np. 16:9, 2.39:1.', max_length=80, verbose_name='format obrazu'),
        ),
        migrations.AddField(
            model_name='title',
            name='audio_languages',
            field=models.CharField(blank=True, max_length=255, verbose_name='jezyki audio'),
        ),
        migrations.AddField(
            model_name='title',
            name='cast',
            field=models.TextField(blank=True, verbose_name='obsada'),
        ),
        migrations.AddField(
            model_name='title',
            name='color_mode',
            field=models.CharField(blank=True, help_text='Np. kolor, czarno-bialy.', max_length=80, verbose_name='kolor'),
        ),
        migrations.AddField(
            model_name='title',
            name='director',
            field=models.CharField(blank=True, max_length=255, verbose_name='rezyser'),
        ),
        migrations.AddField(
            model_name='title',
            name='discs_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='liczba nosnikow'),
        ),
        migrations.AddField(
            model_name='title',
            name='dubbing_languages',
            field=models.CharField(blank=True, max_length=255, verbose_name='dubbing'),
        ),
        migrations.AddField(
            model_name='title',
            name='ean',
            field=models.CharField(blank=True, max_length=32, verbose_name='EAN / GTIN'),
        ),
        migrations.AddField(
            model_name='title',
            name='genre',
            field=models.CharField(blank=True, max_length=255, verbose_name='gatunek'),
        ),
        migrations.AddField(
            model_name='title',
            name='lector_languages',
            field=models.CharField(blank=True, max_length=255, verbose_name='lektor'),
        ),
        migrations.AddField(
            model_name='title',
            name='marketplace_category_id',
            field=models.CharField(blank=True, max_length=80, verbose_name='ID kategorii marketplace'),
        ),
        migrations.AddField(
            model_name='title',
            name='marketplace_category_name',
            field=models.CharField(blank=True, default='Filmy', max_length=255, verbose_name='kategoria marketplace'),
        ),
        migrations.AddField(
            model_name='title',
            name='marketplace_condition',
            field=models.CharField(choices=[('new', 'Nowy'), ('used', 'Uzywany'), ('refurbished', 'Odnowiony')], default='new', max_length=40, verbose_name='stan produktu'),
        ),
        migrations.AddField(
            model_name='title',
            name='marketplace_description',
            field=models.TextField(blank=True, verbose_name='opis marketplace'),
        ),
        migrations.AddField(
            model_name='title',
            name='marketplace_tags',
            field=models.CharField(blank=True, max_length=255, verbose_name='tagi marketplace'),
        ),
        migrations.AddField(
            model_name='title',
            name='media_type',
            field=models.CharField(blank=True, choices=[('dvd', 'DVD'), ('blu_ray', 'Blu-ray'), ('uhd_blu_ray', '4K UHD Blu-ray'), ('dvd_blu_ray', 'DVD + Blu-ray'), ('digital', 'Digital'), ('vhs', 'VHS'), ('other', 'Inny')], max_length=40, verbose_name='rodzaj nosnika'),
        ),
        migrations.AddField(
            model_name='title',
            name='music_by',
            field=models.CharField(blank=True, max_length=255, verbose_name='muzyka'),
        ),
        migrations.AddField(
            model_name='title',
            name='package_type',
            field=models.CharField(blank=True, help_text='Np. plastikowe, steelbook, digipack.', max_length=120, verbose_name='opakowanie'),
        ),
        migrations.AddField(
            model_name='title',
            name='region_code',
            field=models.CharField(blank=True, help_text='Np. 2, B, region free.', max_length=40, verbose_name='kod regionu'),
        ),
        migrations.AddField(
            model_name='title',
            name='release_edition',
            field=models.CharField(blank=True, help_text='Np. standard, steelbook, kolekcjonerskie.', max_length=120, verbose_name='wydanie'),
        ),
        migrations.AddField(
            model_name='title',
            name='screenwriter',
            field=models.CharField(blank=True, max_length=255, verbose_name='scenariusz'),
        ),
        migrations.AddField(
            model_name='title',
            name='subtitle_languages',
            field=models.CharField(blank=True, max_length=255, verbose_name='napisy'),
        ),
    ]
