# Generated by Django 5.2.15 on 2026-07-03 11:34

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_title_age_rating_title_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaReportImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='cinema_report_imports/', verbose_name='plik raportu kina')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='oryginalna nazwa pliku')),
                ('status', models.CharField(choices=[('uploaded', 'wgrany'), ('parsed', 'rozpoznany'), ('needs_review', 'do weryfikacji'), ('approved', 'zaakceptowany'), ('rejected', 'odrzucony'), ('imported', 'zaimportowany')], default='uploaded', max_length=30, verbose_name='status')),
                ('parsed_at', models.DateTimeField(blank=True, null=True, verbose_name='data rozpoznania')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='data importu')),
                ('parser_notes', models.TextField(blank=True, verbose_name='uwagi parsera')),
            ],
            options={
                'verbose_name': 'import raportu kina',
                'verbose_name_plural': 'importy raportow kin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CinemaReportImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('uploaded', 'wgrany'), ('parsed', 'rozpoznany'), ('needs_review', 'do weryfikacji'), ('approved', 'zaakceptowany'), ('rejected', 'odrzucony'), ('imported', 'zaimportowany')], default='needs_review', max_length=30, verbose_name='status')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='miasto')),
                ('date_from', models.DateField(blank=True, null=True, verbose_name='data od')),
                ('date_to', models.DateField(blank=True, null=True, verbose_name='data do')),
                ('screenings', models.PositiveIntegerField(default=0, verbose_name='liczba seansow')),
                ('admissions', models.PositiveIntegerField(default=0, verbose_name='widzowie')),
                ('box_office_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='box office brutto')),
                ('distributor_share_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, verbose_name='udzial dystrybutora %')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta')),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='pewnosc rozpoznania %')),
                ('source_line', models.TextField(blank=True, verbose_name='linia zrodla')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='surowe dane')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='distribution.cinemabooking', verbose_name='utworzony booking')),
                ('cinema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_import_rows', to='distribution.counterparty', verbose_name='kino/siec')),
                ('report_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='distribution.cinemareportimport', verbose_name='import')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_import_rows', to='distribution.title', verbose_name='tytul')),
            ],
            options={
                'verbose_name': 'wiersz importu raportu kina',
                'verbose_name_plural': 'wiersze importu raportow kin',
                'ordering': ['report_import', 'date_from', 'title__title_pl'],
            },
        ),
    ]
