# Generated by Django 5.2.15 on 2026-07-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_cinemareportimport_cinemareportimportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemabooking',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Import ID / ref'),
        ),
    ]
