# Generated by Django 5.2.15 on 2026-07-03 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_cinemabooking_source_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.CharField(choices=[('dcp', 'DCP'), ('kdm', 'KDM'), ('trailer', 'Trailer'), ('poster', 'Plakat / key art'), ('stills', 'Fotosy'), ('subtitles', 'Napisy'), ('dubbing', 'Dubbing'), ('voiceover', 'Lektor'), ('audio', 'Audio'), ('master', 'Master / mezzanine'), ('qc_report', 'Raport QC'), ('certificate', 'Certyfikat / klasyfikacja'), ('press_kit', 'Press kit'), ('platform_package', 'Pakiet platformy'), ('other', 'Inne')], max_length=40, verbose_name='typ materiału')),
                ('exploitation_field', models.CharField(blank=True, choices=[('cinema', 'Kino'), ('festivals', 'Festiwale'), ('non_theatrical', 'Non-theatrical / edukacja'), ('linear_tv', 'TV linearna'), ('pay_tv', 'Pay TV'), ('free_tv', 'Free TV'), ('svod', 'SVOD'), ('tvod', 'TVOD'), ('est', 'EST / DTO'), ('avod', 'AVOD'), ('fast', 'FAST'), ('airlines', 'Linie lotnicze'), ('hotels', 'Hotele / hospitality'), ('clips', 'Clips / fragmenty'), ('promo_internet', 'Internet promocyjny'), ('home_video', 'Home video / DVD / Blu-ray'), ('other', 'Inne')], max_length=40, verbose_name='pole eksploatacji')),
                ('status', models.CharField(choices=[('missing', 'brak'), ('ordered', 'zamówione'), ('in_progress', 'w przygotowaniu'), ('ready', 'gotowe'), ('sent', 'wysłane'), ('accepted', 'zaakceptowane'), ('rejected', 'odrzucone / do poprawy')], default='missing', max_length=30, verbose_name='status')),
                ('required_for_release', models.BooleanField(default=True, verbose_name='wymagane do startu eksploatacji?')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='termin')),
                ('delivered_at', models.DateField(blank=True, null=True, verbose_name='data dostarczenia')),
                ('file', models.FileField(blank=True, upload_to='title_materials/', verbose_name='plik')),
                ('external_reference', models.CharField(blank=True, max_length=255, verbose_name='link / ID zewnętrzne')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('language_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='distribution.languageversion', verbose_name='wersja językowa')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_materials', to='distribution.counterparty', verbose_name='dostawca')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='distribution.title', verbose_name='tytuł')),
            ],
            options={
                'verbose_name': 'materiał / delivery',
                'verbose_name_plural': 'materiały / delivery',
                'ordering': ['title__title_pl', 'asset_type', 'exploitation_field', 'due_date'],
                'indexes': [models.Index(fields=['title', 'status'], name='distributio_title_i_32968e_idx'), models.Index(fields=['asset_type', 'status'], name='distributio_asset_t_e73ad3_idx'), models.Index(fields=['due_date'], name='distributio_due_dat_4fbdda_idx')],
            },
        ),
    ]
