# Generated by Django 5.2.15 on 2026-07-03 13:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_titlematerial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterfallParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participation_type', models.CharField(choices=[('licensor', 'Licensor'), ('producer', 'Producer'), ('investor', 'Investor'), ('talent', 'Talent'), ('sales_agent', 'Sales agent'), ('other', 'Other')], default='licensor', max_length=30, verbose_name='typ uczestnika')),
                ('share_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='udzial %')),
                ('payout_cap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 oznacza brak limitu.', max_digits=14, verbose_name='limit wyplaty / cap')),
                ('paid_to_date', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='wyplacone przed tym okresem')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='kolejnosc')),
                ('active', models.BooleanField(default=True, verbose_name='aktywny?')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waterfall_participations', to='distribution.counterparty', verbose_name='uczestnik / odbiorca')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='distribution.waterfallrecoupmentrule', verbose_name='waterfall / recoupment')),
            ],
            options={
                'verbose_name': 'uczestnik waterfall',
                'verbose_name_plural': 'uczestnicy waterfall',
                'ordering': ['rule', 'sort_order', 'recipient__name'],
                'indexes': [models.Index(fields=['rule', 'active', 'sort_order'], name='distributio_rule_id_aa37df_idx'), models.Index(fields=['recipient'], name='distributio_recipie_f3e854_idx')],
            },
        ),
        migrations.CreateModel(
            name='WaterfallRecoupmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('mg', 'MG / advance'), ('pa', 'P&A'), ('delivery', 'Delivery / materials'), ('legal', 'Legal'), ('costs', 'Costs from ledger'), ('other', 'Other')], default='other', max_length=30, verbose_name='typ pozycji')),
                ('name', models.CharField(max_length=160, verbose_name='nazwa')),
                ('priority', models.PositiveIntegerField(default=100, help_text='Nizszy numer oznacza wczesniejsze odzyskiwanie.', verbose_name='priorytet')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='kwota do odzyskania')),
                ('recouped_to_date', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='odzyskane przed tym okresem')),
                ('active', models.BooleanField(default=True, verbose_name='aktywny?')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoupment_items', to='distribution.waterfallrecoupmentrule', verbose_name='waterfall / recoupment')),
            ],
            options={
                'verbose_name': 'pozycja recoupmentu',
                'verbose_name_plural': 'pozycje recoupmentu',
                'ordering': ['rule', 'priority', 'item_type', 'name'],
                'indexes': [models.Index(fields=['rule', 'active', 'priority'], name='distributio_rule_id_d4e56e_idx'), models.Index(fields=['item_type'], name='distributio_item_ty_c0f450_idx')],
            },
        ),
    ]
