# Generated by Django 5.2.16 on 2026-07-16 16:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0009_waterfallparticipant_waterfallrecoupmentitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='royaltystatement',
            name='calculated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='przeliczono'),
        ),
        migrations.AddField(
            model_name='royaltystatement',
            name='calculation_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='zamrozona kalkulacja'),
        ),
        migrations.AddField(
            model_name='royaltystatement',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='zablokowano'),
        ),
        migrations.CreateModel(
            name='WaterfallPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Glowny waterfall', max_length=180, verbose_name='nazwa planu')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='wersja')),
                ('status', models.CharField(choices=[('draft', 'roboczy'), ('active', 'aktywny'), ('archived', 'archiwalny')], default='draft', max_length=20, verbose_name='status')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='obowiazuje od')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='obowiazuje do')),
                ('applies_to_all_exploitation_fields', models.BooleanField(default=True, verbose_name='wszystkie pola eksploatacji?')),
                ('exploitation_fields', models.JSONField(blank=True, default=list, verbose_name='pola eksploatacji')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi / podstawa umowna')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterfall_plans', to='distribution.title', verbose_name='tytul')),
            ],
            options={
                'verbose_name': 'waterfall 2.0 - plan',
                'verbose_name_plural': 'waterfall 2.0 - plany',
                'ordering': ['title__title_pl', 'name', '-version'],
            },
        ),
        migrations.AddField(
            model_name='royaltystatement',
            name='waterfall_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalty_statements', to='distribution.waterfallplan', verbose_name='plan waterfall 2.0'),
        ),
        migrations.CreateModel(
            name='WaterfallRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(verbose_name='okres od')),
                ('period_end', models.DateField(verbose_name='okres do')),
                ('status', models.CharField(choices=[('draft', 'roboczy'), ('finalized', 'zatwierdzony'), ('void', 'anulowany')], default='draft', max_length=20, verbose_name='status')),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='gross revenue')),
                ('net_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='net revenue')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='rozdzielono')),
                ('closing_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='pozostalo po waterfall')),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict, verbose_name='snapshot kalkulacji')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='przeliczono')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='zatwierdzono')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_waterfall_runs', to=settings.AUTH_USER_MODEL, verbose_name='zatwierdzil')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='distribution.waterfallplan', verbose_name='plan waterfall')),
            ],
            options={
                'verbose_name': 'waterfall 2.0 - uruchomienie',
                'verbose_name_plural': 'waterfall 2.0 - uruchomienia',
                'ordering': ['-period_end', 'plan__title__title_pl', 'plan__name'],
            },
        ),
        migrations.AddField(
            model_name='royaltystatement',
            name='waterfall_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalty_statements', to='distribution.waterfallrun', verbose_name='uruchomienie waterfall 2.0'),
        ),
        migrations.CreateModel(
            name='WaterfallStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.PositiveIntegerField(default=0, help_text='Np. 0: fee/P&A/MG, 1: hard money, 2: PISF, 3: profit split.', verbose_name='faza')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='kolejnosc')),
                ('name', models.CharField(max_length=180, verbose_name='nazwa kroku')),
                ('step_type', models.CharField(choices=[('commission', 'prowizja / fee'), ('deduction', 'potracenie'), ('recoupment', 'zwrot / recoupment'), ('split', 'podzial wplywow'), ('reserve', 'rezerwa / holdback')], max_length=30, verbose_name='typ kroku')),
                ('allocation_mode', models.CharField(choices=[('sequential', 'kolejno'), ('pro_rata', 'pro rata'), ('pari_passu', 'pari passu')], default='sequential', max_length=30, verbose_name='sposob alokacji')),
                ('percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='procent z dostepnej podstawy')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='kwota stala')),
                ('target_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='kwota do odzyskania')),
                ('premium_percent', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7, verbose_name='premia / uplift %')),
                ('opening_recouped', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='odzyskane przed FILMERP')),
                ('cap_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='0 oznacza brak limitu.', max_digits=16, verbose_name='limit laczny / cap')),
                ('include_title_mg', models.BooleanField(default=False, verbose_name='dolicz MG tytulu do celu?')),
                ('include_recoupable_costs', models.BooleanField(default=False, verbose_name='dolicz koszty recoupable do celu?')),
                ('cost_categories', models.JSONField(blank=True, default=list, help_text='Puste oznacza wszystkie kategorie kosztow recoupable.', verbose_name='kategorie kosztow')),
                ('exploitation_fields', models.JSONField(blank=True, default=list, help_text='Puste oznacza zakres calego planu.', verbose_name='ogranicz krok do pol')),
                ('active', models.BooleanField(default=True, verbose_name='aktywny?')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi / klauzula umowna')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waterfall_steps', to='distribution.counterparty', verbose_name='beneficjent')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='distribution.waterfallplan', verbose_name='plan waterfall')),
            ],
            options={
                'verbose_name': 'waterfall 2.0 - krok',
                'verbose_name_plural': 'waterfall 2.0 - kroki',
                'ordering': ['plan', 'phase', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WaterfallRunLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(verbose_name='kolejnosc')),
                ('phase', models.PositiveIntegerField(verbose_name='faza')),
                ('opening_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='dostepne przed krokiem')),
                ('calculation_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='podstawa kalkulacji')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='alokacja')),
                ('closing_available', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='dostepne po kroku')),
                ('opening_recoupment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='saldo recoupment przed')),
                ('closing_recoupment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='saldo recoupment po')),
                ('calculation_details', models.JSONField(blank=True, default=dict, verbose_name='szczegoly')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waterfall_run_lines', to='distribution.counterparty', verbose_name='beneficjent')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='distribution.waterfallrun', verbose_name='uruchomienie')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='run_lines', to='distribution.waterfallstep', verbose_name='krok')),
            ],
            options={
                'verbose_name': 'waterfall 2.0 - linia kalkulacji',
                'verbose_name_plural': 'waterfall 2.0 - linie kalkulacji',
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='waterfallplan',
            constraint=models.UniqueConstraint(fields=('title', 'name', 'version'), name='unique_waterfall_plan_version'),
        ),
        migrations.AddIndex(
            model_name='waterfallrun',
            index=models.Index(fields=['plan', 'status', 'period_start', 'period_end'], name='distributio_plan_id_3a9354_idx'),
        ),
        migrations.AddIndex(
            model_name='waterfallstep',
            index=models.Index(fields=['plan', 'active', 'phase', 'sort_order'], name='distributio_plan_id_da9982_idx'),
        ),
        migrations.AddConstraint(
            model_name='waterfallrunline',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='unique_waterfall_run_sequence'),
        ),
    ]
