# Generated by Django 5.2.16 on 2026-07-17 15:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_royaltystatement_calculated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentInboxItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_file', models.FileField(upload_to='document_inbox/%Y/%m/', verbose_name='dokument źródłowy')),
                ('original_filename', models.CharField(max_length=255, verbose_name='oryginalna nazwa')),
                ('file_hash', models.CharField(max_length=64, unique=True, verbose_name='SHA-256')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='typ MIME')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='rozmiar pliku')),
                ('document_type', models.CharField(choices=[('unknown', 'nierozpoznany'), ('cinema_report', 'raport seansów / box office'), ('cinema_statement', 'statement kina'), ('cost_invoice', 'faktura kosztowa'), ('other', 'inny dokument')], default='unknown', max_length=40, verbose_name='rodzaj dokumentu')),
                ('status', models.CharField(choices=[('uploaded', 'wgrany'), ('needs_review', 'do weryfikacji'), ('processed', 'zaksięgowany'), ('rejected', 'odrzucony')], default='uploaded', max_length=30, verbose_name='status')),
                ('classification_confidence', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='pewność klasyfikacji %')),
                ('extracted_data', models.JSONField(blank=True, default=dict, verbose_name='rozpoznane dane')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='data zaksięgowania')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('cinema_import', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_document', to='distribution.cinemareportimport', verbose_name='import raportu kina')),
                ('cost', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_document', to='distribution.cost', verbose_name='utworzony koszt')),
                ('counterparty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_documents', to='distribution.counterparty', verbose_name='kontrahent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_inbox_documents', to=settings.AUTH_USER_MODEL, verbose_name='zweryfikował')),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_documents', to='distribution.title', verbose_name='tytuł')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_inbox_documents', to=settings.AUTH_USER_MODEL, verbose_name='wgrał')),
            ],
            options={
                'verbose_name': 'dokument w kolejce',
                'verbose_name_plural': 'centrum dokumentów',
                'ordering': ['-created_at'],
            },
        ),
    ]
