# Generated by Django 5.2.16 on 2026-07-17 20:27

import django.db.models.deletion
from django.db import migrations, models


def migrate_legacy_waterfalls(apps, schema_editor):
    LegacyRule = apps.get_model('distribution', 'WaterfallRecoupmentRule')
    WaterfallPlan = apps.get_model('distribution', 'WaterfallPlan')
    WaterfallStep = apps.get_model('distribution', 'WaterfallStep')

    title_ids_with_plans = set(WaterfallPlan.objects.values_list('title_id', flat=True))
    rules = LegacyRule.objects.select_related('title').prefetch_related('recoupment_items', 'participants__recipient')
    for rule in rules.order_by('title_id', 'id'):
        if rule.title_id in title_ids_with_plans:
            continue

        plan = WaterfallPlan.objects.create(
            title_id=rule.title_id,
            name=f"Waterfall {rule.exploitation_field}",
            version=1,
            status='active' if rule.active else 'archived',
            currency=rule.currency,
            applies_to_all_exploitation_fields=False,
            exploitation_fields=[rule.exploitation_field],
            notes=f"Automatycznie przeniesiono ze starej reguły #{rule.pk}.",
        )
        steps = []

        def add_fee(order):
            if rule.distributor_fee_percent:
                steps.append(WaterfallStep(
                    plan_id=plan.pk,
                    phase=0,
                    sort_order=order,
                    name='Fee dystrybutora',
                    step_type='commission',
                    allocation_mode='sequential',
                    percentage=rule.distributor_fee_percent,
                    exploitation_fields=[rule.exploitation_field],
                    notes=f"Przeniesiono ze starej reguły #{rule.pk}.",
                ))

        if not rule.fee_after_recoupment:
            add_fee(10)

        if rule.recoupment_pool or rule.include_recoupable_costs:
            steps.append(WaterfallStep(
                plan_id=plan.pk,
                phase=0,
                sort_order=20,
                name='Bazowy recoupment i koszty',
                step_type='recoupment',
                allocation_mode='sequential',
                target_amount=rule.recoupment_pool,
                include_recoupable_costs=rule.include_recoupable_costs,
                exploitation_fields=[rule.exploitation_field],
                notes=f"Przeniesiono ze starej reguły #{rule.pk}.",
            ))

        for position, item in enumerate(rule.recoupment_items.filter(active=True).order_by('priority', 'id'), start=1):
            steps.append(WaterfallStep(
                plan_id=plan.pk,
                phase=0,
                sort_order=20 + position,
                name=item.name,
                step_type='recoupment',
                allocation_mode='sequential',
                target_amount=item.amount,
                opening_recouped=item.recouped_to_date,
                exploitation_fields=[rule.exploitation_field],
                notes=item.notes,
            ))

        if rule.fee_after_recoupment:
            add_fee(80)

        participants = list(rule.participants.filter(active=True).order_by('sort_order', 'id'))
        for position, participant in enumerate(participants, start=1):
            remaining_cap = max(participant.payout_cap - participant.paid_to_date, 0) if participant.payout_cap else 0
            steps.append(WaterfallStep(
                plan_id=plan.pk,
                phase=1,
                sort_order=position * 10,
                name=f"Udział: {participant.recipient.name}",
                step_type='split',
                allocation_mode='pari_passu',
                beneficiary_id=participant.recipient_id,
                percentage=participant.share_percent,
                cap_amount=remaining_cap,
                exploitation_fields=[rule.exploitation_field],
                notes=participant.notes,
            ))

        if not participants and rule.participant_share_percent and rule.title.producer_id:
            steps.append(WaterfallStep(
                plan_id=plan.pk,
                phase=1,
                sort_order=10,
                name='Udział producenta / licencjodawcy',
                step_type='split',
                allocation_mode='pari_passu',
                beneficiary_id=rule.title.producer_id,
                percentage=rule.participant_share_percent,
                exploitation_fields=[rule.exploitation_field],
                notes=f"Udział przeniesiono ze starej reguły #{rule.pk}.",
            ))

        WaterfallStep.objects.bulk_create(steps)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0011_documentinboxitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waterfallplan',
            options={'ordering': ['title__title_pl', 'name', '-version'], 'verbose_name': 'plan waterfall', 'verbose_name_plural': 'plany waterfall'},
        ),
        migrations.AlterModelOptions(
            name='waterfallrun',
            options={'ordering': ['-period_end', 'plan__title__title_pl', 'plan__name'], 'verbose_name': 'rozliczenie waterfall okresu', 'verbose_name_plural': 'rozliczenia waterfall okresów'},
        ),
        migrations.AlterModelOptions(
            name='waterfallrunline',
            options={'ordering': ['run', 'sequence'], 'verbose_name': 'pozycja kalkulacji waterfall', 'verbose_name_plural': 'pozycje kalkulacji waterfall'},
        ),
        migrations.AlterModelOptions(
            name='waterfallstep',
            options={'ordering': ['plan', 'phase', 'sort_order', 'id'], 'verbose_name': 'krok waterfall', 'verbose_name_plural': 'kroki waterfall'},
        ),
        migrations.AlterField(
            model_name='royaltystatement',
            name='waterfall_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalty_statements', to='distribution.waterfallplan', verbose_name='plan waterfall'),
        ),
        migrations.AlterField(
            model_name='royaltystatement',
            name='waterfall_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='royalty_statements', to='distribution.waterfallrun', verbose_name='rozliczenie waterfall okresu'),
        ),
        migrations.AlterField(
            model_name='waterfallrunline',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='distribution.waterfallrun', verbose_name='rozliczenie okresu'),
        ),
        migrations.RunPython(migrate_legacy_waterfalls, noop_reverse),
    ]
