# Generated by Django 5.2.16 on 2026-07-19 20:04

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def migrate_cost_scopes(apps, schema_editor):
    Cost = apps.get_model('distribution', 'Cost')
    updates = []
    for cost in Cost.objects.all().iterator():
        selected = []
        for value in (cost.exploitation_fields or '').split(','):
            value = value.strip()
            if value and value not in selected:
                selected.append(value)
        if cost.exploitation_field and cost.exploitation_field not in selected:
            selected.append(cost.exploitation_field)

        if cost.applies_to_all_exploitation_fields or not selected:
            cost.scope_mode = 'all'
            cost.scope_fields = []
        else:
            cost.scope_mode = 'selected'
            cost.scope_fields = selected
        cost.allocation_percentages = {}
        updates.append(cost)

    if updates:
        Cost.objects.bulk_update(updates, ['scope_mode', 'scope_fields', 'allocation_percentages'])


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0012_alter_waterfallplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='allocation_percentages',
            field=models.JSONField(blank=True, default=dict, verbose_name='podział procentowy na pola'),
        ),
        migrations.AddField(
            model_name='cost',
            name='scope_fields',
            field=models.JSONField(blank=True, default=list, verbose_name='wybrane pola eksploatacji'),
        ),
        migrations.AddField(
            model_name='cost',
            name='scope_mode',
            field=models.CharField(choices=[('all', 'Wszystkie pola'), ('selected', 'Wybrane pola'), ('allocated', 'Podział procentowy')], default='all', max_length=20, verbose_name='zakres kosztu'),
        ),
        migrations.RunPython(migrate_cost_scopes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cost',
            name='applies_to_all_exploitation_fields',
            field=models.BooleanField(default=False, editable=False, verbose_name='dotyczy wszystkich pol eksploatacji?'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='exploitation_field',
            field=models.CharField(blank=True, choices=[('cinema', 'Kino'), ('festivals', 'Festiwale'), ('non_theatrical', 'Non-theatrical / edukacja'), ('linear_tv', 'TV linearna'), ('pay_tv', 'Pay TV'), ('free_tv', 'Free TV'), ('svod', 'SVOD'), ('tvod', 'TVOD'), ('est', 'EST / DTO'), ('avod', 'AVOD'), ('fast', 'FAST'), ('airlines', 'Linie lotnicze'), ('hotels', 'Hotele / hospitality'), ('clips', 'Clips / fragmenty'), ('promo_internet', 'Internet promocyjny'), ('home_video', 'Home video / DVD / Blu-ray'), ('other', 'Inne')], editable=False, max_length=40, verbose_name='pole eksploatacji'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='exploitation_fields',
            field=models.TextField(blank=True, editable=False, help_text='Lista pol oddzielona przecinkami. Uzywane do przypisania kosztu do wielu pol w waterfall.', verbose_name='pola eksploatacji dla waterfall'),
        ),
        migrations.CreateModel(
            name='WaterfallRunCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exploitation_field', models.CharField(blank=True, choices=[('cinema', 'Kino'), ('festivals', 'Festiwale'), ('non_theatrical', 'Non-theatrical / edukacja'), ('linear_tv', 'TV linearna'), ('pay_tv', 'Pay TV'), ('free_tv', 'Free TV'), ('svod', 'SVOD'), ('tvod', 'TVOD'), ('est', 'EST / DTO'), ('avod', 'AVOD'), ('fast', 'FAST'), ('airlines', 'Linie lotnicze'), ('hotels', 'Hotele / hospitality'), ('clips', 'Clips / fragmenty'), ('promo_internet', 'Internet promocyjny'), ('home_video', 'Home video / DVD / Blu-ray'), ('other', 'Inne')], max_length=40, verbose_name='część pola eksploatacji')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='odzyskana kwota')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waterfall_allocations', to='distribution.cost', verbose_name='koszt / faktura')),
                ('run_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='distribution.waterfallrunline', verbose_name='pozycja waterfall')),
            ],
            options={
                'verbose_name': 'alokacja odzyskanego kosztu',
                'verbose_name_plural': 'alokacje odzyskanych kosztów',
                'ordering': ['run_line', 'cost__cost_date', 'cost_id', 'exploitation_field'],
                'indexes': [models.Index(fields=['cost', 'exploitation_field'], name='distributio_cost_id_2edbfe_idx')],
                'constraints': [models.UniqueConstraint(fields=('run_line', 'cost', 'exploitation_field'), name='unique_run_line_cost_portion')],
            },
        ),
    ]
