# Generated by Django 5.2.16 on 2026-07-19 22:05

import django.core.validators
from decimal import Decimal, ROUND_HALF_UP
from django.db import migrations, models


def infer_existing_vat_rates(apps, schema_editor):
    Cost = apps.get_model("distribution", "Cost")
    costs = Cost.objects.using(schema_editor.connection.alias)
    for cost in costs.all().iterator():
        if cost.net_amount and cost.net_amount > 0 and cost.vat_amount and cost.vat_amount > 0:
            rate = (cost.vat_amount * Decimal("100.00") / cost.net_amount).quantize(
                Decimal("0.01"),
                rounding=ROUND_HALF_UP,
            )
            rate = min(rate, Decimal("100.00"))
        else:
            rate = Decimal("0.00")
        costs.filter(pk=cost.pk).update(vat_rate=rate)


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0013_cost_scope_and_recoupment_ledger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-cost_date', 'title__title_pl'], 'verbose_name': 'koszt P&A i dystrybucji', 'verbose_name_plural': 'koszty P&A i dystrybucji'},
        ),
        migrations.AlterModelOptions(
            name='rightswindow',
            options={'ordering': ['title__title_pl', 'exploitation_field', 'date_from'], 'verbose_name': 'okno praw', 'verbose_name_plural': 'okna praw'},
        ),
        migrations.AlterModelOptions(
            name='titlematerial',
            options={'ordering': ['title__title_pl', 'asset_type', 'exploitation_field', 'due_date'], 'verbose_name': 'materiał tytułu', 'verbose_name_plural': 'materiały tytułu'},
        ),
        migrations.AddField(
            model_name='cost',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.00'), help_text='Stawka procentowa. Kwota VAT i Brutto (VAT) zostaną obliczone automatycznie.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='VAT (%)'),
        ),
        migrations.RunPython(infer_existing_vat_rates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cost',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Kwota bez VAT z faktury.', max_digits=14, verbose_name='Netto (VAT)'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14, verbose_name='kwota VAT'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='potrącenia'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='gross_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Przychód przed potrąceniami dystrybucyjnymi. Nie jest to kwota brutto z VAT.', max_digits=14, verbose_name='Brutto'),
        ),
        migrations.AlterField(
            model_name='salesreport',
            name='vat_withholding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='podatki i potrącenia u źródła'),
        ),
        migrations.AlterField(
            model_name='waterfallrun',
            name='gross_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Brutto'),
        ),
        migrations.AlterField(
            model_name='waterfallrun',
            name='net_revenue',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16, verbose_name='Netto'),
        ),
    ]
