# Generated by Django 5.2.16 on 2026-07-20 09:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('distribution', '0014_alter_cost_options_alter_rightswindow_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mfa_required', models.BooleanField(default=False, verbose_name='wymagaj MFA')),
                ('force_password_change', models.BooleanField(default=False, verbose_name='wymagaj zmiany hasla')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='zaproszono')),
                ('invitation_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='wyslano zaproszenie')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='dezaktywowano')),
                ('deactivation_reason', models.CharField(blank=True, max_length=255, verbose_name='powod dezaktywacji')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatnia aktywnosc')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ostatni adres IP')),
                ('last_login_user_agent', models.TextField(blank=True, verbose_name='ostatnie urzadzenie')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi bezpieczenstwa')),
                ('deactivated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_accounts_deactivated', to=settings.AUTH_USER_MODEL, verbose_name='dezaktywowany przez')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_invitations_sent', to=settings.AUTH_USER_MODEL, verbose_name='zaproszony przez')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL, verbose_name='uzytkownik')),
            ],
            options={
                'verbose_name': 'profil bezpieczenstwa',
                'verbose_name_plural': 'profile bezpieczenstwa',
                'permissions': [('manage_users', 'Moze zarzadzac uzytkownikami i rolami'), ('view_security_log', 'Moze przegladac historie logowan'), ('view_business_audit', 'Moze przegladac historie zmian'), ('export_audit_log', 'Moze eksportowac dzienniki audytowe'), ('revoke_sessions', 'Moze konczyc sesje uzytkownikow'), ('approve_cinema_reports', 'Moze zatwierdzac raporty kinowe'), ('finalize_waterfalls', 'Moze finalizowac rozliczenia waterfall'), ('generate_statements', 'Moze generowac statementy'), ('send_statements', 'Moze oznaczac statementy jako wyslane'), ('mark_statements_paid', 'Moze oznaczac statementy jako oplacone'), ('export_financial_data', 'Moze eksportowac dane finansowe')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='czas zdarzenia')),
                ('integrity_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='podpis integralnosci')),
                ('action', models.CharField(choices=[('create', 'Utworzenie'), ('update', 'Zmiana'), ('delete', 'Usuniecie'), ('approve', 'Zatwierdzenie'), ('reject', 'Odrzucenie'), ('import', 'Import'), ('export', 'Eksport'), ('finalize', 'Finalizacja'), ('send', 'Wysylka'), ('status', 'Zmiana statusu'), ('role', 'Zmiana roli'), ('permission', 'Zmiana uprawnien'), ('force_logout', 'Zakonczenie sesji'), ('security', 'Zmiana zabezpieczen'), ('access', 'Dostep do danych'), ('system', 'Operacja systemowa')], db_index=True, max_length=30, verbose_name='akcja')),
                ('source', models.CharField(db_index=True, default='dashboard', max_length=30, verbose_name='zrodlo')),
                ('module', models.CharField(db_index=True, max_length=80, verbose_name='modul')),
                ('object_pk', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ID obiektu')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='obiekt')),
                ('summary', models.CharField(max_length=500, verbose_name='opis')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='zmiany')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='dane dodatkowe')),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='identyfikator zadania')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adres IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('retention_class', models.CharField(choices=[('ordinary', 'Zwykly'), ('legal_financial', 'Prawny lub finansowy'), ('security', 'Bezpieczenstwo')], db_index=True, default='ordinary', max_length=30, verbose_name='klasa retencji')),
                ('legacy_reference', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='referencja archiwalna')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filmerp_audit_events', to=settings.AUTH_USER_MODEL, verbose_name='wykonawca')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'zdarzenie audytowe',
                'verbose_name_plural': 'zdarzenia audytowe',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['actor', '-occurred_at'], name='distributio_actor_i_74014f_idx'), models.Index(fields=['module', 'action', '-occurred_at'], name='distributio_module_fa12d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='czas zdarzenia')),
                ('integrity_hash', models.CharField(blank=True, editable=False, max_length=64, verbose_name='podpis integralnosci')),
                ('event_type', models.CharField(choices=[('login_success', 'Logowanie udane'), ('login_failure', 'Logowanie nieudane'), ('locked', 'Konto czasowo zablokowane'), ('unlocked', 'Konto odblokowane'), ('logout_manual', 'Wylogowanie reczne'), ('logout_idle', 'Wylogowanie po bezczynnosci'), ('logout_forced', 'Wylogowanie wymuszone'), ('session_expired', 'Sesja wygasla'), ('password_changed', 'Zmiana hasla'), ('password_reset', 'Reset hasla'), ('mfa_success', 'MFA poprawne'), ('mfa_failure', 'MFA niepoprawne'), ('mfa_enabled', 'MFA wlaczone'), ('mfa_disabled', 'MFA wylaczone'), ('mfa_recovery_used', 'Uzyto kodu zapasowego')], db_index=True, max_length=40, verbose_name='zdarzenie')),
                ('result', models.CharField(db_index=True, default='success', max_length=20, verbose_name='wynik')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='powod')),
                ('identifier', models.CharField(blank=True, max_length=255, verbose_name='identyfikator')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True, verbose_name='adres IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('browser', models.CharField(blank=True, max_length=120, verbose_name='przegladarka')),
                ('operating_system', models.CharField(blank=True, max_length=120, verbose_name='system')),
                ('device', models.CharField(blank=True, max_length=120, verbose_name='urzadzenie')),
                ('session_fingerprint', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='odcisk sesji')),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='identyfikator zadania')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='dane dodatkowe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_events', to=settings.AUTH_USER_MODEL, verbose_name='uzytkownik')),
            ],
            options={
                'verbose_name': 'zdarzenie logowania',
                'verbose_name_plural': 'zdarzenia logowania',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='distributio_user_id_eb7f93_idx')],
            },
        ),
    ]
