# Generated by Django 5.2.16 on 2026-07-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0017_require_mfa_for_existing_superusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Logowanie udane'), ('login_failure', 'Logowanie nieudane'), ('locked', 'Konto czasowo zablokowane'), ('unlocked', 'Konto odblokowane'), ('logout_manual', 'Wylogowanie reczne'), ('logout_idle', 'Wylogowanie po bezczynnosci'), ('logout_forced', 'Wylogowanie wymuszone'), ('session_expired', 'Sesja wygasla'), ('session_changed', 'Zmiana urzadzenia sesji'), ('password_changed', 'Zmiana hasla'), ('password_reset', 'Reset hasla'), ('mfa_success', 'MFA poprawne'), ('mfa_failure', 'MFA niepoprawne'), ('mfa_enabled', 'MFA wlaczone'), ('mfa_disabled', 'MFA wylaczone'), ('mfa_recovery_used', 'Uzyto kodu zapasowego')], db_index=True, max_length=40, verbose_name='zdarzenie'),
        ),
    ]
