# Generated by Django 5.2.16 on 2026-07-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0018_alter_loginevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(choices=[('create', 'Utworzenie'), ('update', 'Zmiana'), ('delete', 'Usunięcie'), ('approve', 'Zatwierdzenie'), ('reject', 'Odrzucenie'), ('import', 'Import'), ('export', 'Eksport'), ('finalize', 'Finalizacja'), ('send', 'Wysyłka'), ('status', 'Zmiana statusu'), ('role', 'Zmiana roli'), ('permission', 'Zmiana uprawnień'), ('force_logout', 'Zakończenie sesji'), ('security', 'Zmiana zabezpieczeń'), ('access', 'Dostęp do danych'), ('system', 'Operacja systemowa')], db_index=True, max_length=30, verbose_name='akcja'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Logowanie udane'), ('login_failure', 'Logowanie nieudane'), ('locked', 'Konto czasowo zablokowane'), ('unlocked', 'Konto odblokowane'), ('logout_manual', 'Wylogowanie ręczne'), ('logout_idle', 'Wylogowanie po bezczynności'), ('logout_forced', 'Wylogowanie wymuszone'), ('session_expired', 'Sesja wygasła'), ('session_changed', 'Zmiana urządzenia sesji'), ('password_changed', 'Zmiana hasła'), ('password_reset', 'Reset hasła'), ('mfa_success', 'MFA poprawne'), ('mfa_failure', 'MFA niepoprawne'), ('mfa_enabled', 'MFA włączone'), ('mfa_disabled', 'MFA wyłączone'), ('mfa_recovery_used', 'Użyto kodu zapasowego')], db_index=True, max_length=40, verbose_name='zdarzenie'),
        ),
    ]
