# Generated by Django 5.2.16 on 2026-07-20 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0019_alter_auditevent_action_alter_loginevent_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityprofile',
            name='mfa_required',
        ),
    ]
