# Generated by Django 5.2.16 on 2026-07-21 14:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0020_remove_securityprofile_mfa_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterparty',
            name='reporting_cycle',
            field=models.CharField(choices=[('none', 'brak'), ('weekly', 'tygodniowy'), ('monthly', 'miesięczny'), ('quarterly', 'kwartalny'), ('semiannual', 'półroczny'), ('annual', 'roczny'), ('event', 'po evencie')], default='none', max_length=30, verbose_name='cykl raportowania'),
        ),
        migrations.AlterField(
            model_name='salesagreement',
            name='reporting_cycle',
            field=models.CharField(choices=[('none', 'brak'), ('weekly', 'tygodniowy'), ('monthly', 'miesięczny'), ('quarterly', 'kwartalny'), ('semiannual', 'półroczny'), ('annual', 'roczny'), ('event', 'po evencie')], default='quarterly', max_length=30, verbose_name='raportowanie'),
        ),
        migrations.CreateModel(
            name='BookingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Premiera kinowa', max_length=180, verbose_name='nazwa kampanii')),
                ('release_date', models.DateField(verbose_name='data premiery')),
                ('status', models.CharField(choices=[('planning', 'Planowanie'), ('booking', 'Booking'), ('in_release', 'W eksploatacji'), ('completed', 'Zakończona'), ('cancelled', 'Anulowana')], default='planning', max_length=24, verbose_name='status')),
                ('target_cinemas', models.PositiveIntegerField(default=0, verbose_name='cel: liczba kin')),
                ('target_screens', models.PositiveIntegerField(default=0, verbose_name='cel: liczba ekranów')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta')),
                ('default_share_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='domyślny udział dystrybutora %')),
                ('notes', models.TextField(blank=True, verbose_name='założenia i uwagi')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_campaigns', to=settings.AUTH_USER_MODEL, verbose_name='opiekun kampanii')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_campaigns', to='distribution.title', verbose_name='tytuł')),
            ],
            options={
                'verbose_name': 'kampania bookingowa',
                'verbose_name_plural': 'kampanie bookingowe',
                'ordering': ['-release_date', 'title__title_pl'],
            },
        ),
        migrations.CreateModel(
            name='BookingDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.CharField(choices=[('target', 'Do kontaktu'), ('contacted', 'Kontakt wykonany'), ('negotiation', 'Negocjacje'), ('offer', 'Oferta'), ('confirmed', 'Potwierdzony'), ('playing', 'Gra'), ('holdover', 'Holdover'), ('ended', 'Zakończony'), ('lost', 'Odrzucony')], default='target', max_length=24, verbose_name='etap')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='początek grania')),
                ('playing_to', models.DateField(blank=True, null=True, verbose_name='planowany koniec')),
                ('expected_screens', models.PositiveIntegerField(default=1, verbose_name='planowane ekrany')),
                ('confirmed_screens', models.PositiveIntegerField(default=0, verbose_name='potwierdzone ekrany')),
                ('minimum_screenings', models.PositiveIntegerField(default=0, verbose_name='minimum seansów')),
                ('settlement_basis', models.CharField(choices=[('gross_vat', 'Box office brutto (sprzedaż biletów z VAT)'), ('net_vat', 'Box office netto (po odjęciu VAT)'), ('fixed', 'Stawka stała'), ('custom', 'Warunki indywidualne')], default='gross_vat', max_length=24, verbose_name='podstawa rozliczenia')),
                ('distributor_share_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='udział dystrybutora %')),
                ('minimum_guarantee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='MG kina')),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='stawka stała')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta')),
                ('screen_format', models.CharField(blank=True, help_text='Np. DCP 2D, IMAX, 4K.', max_length=80, verbose_name='format')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='ostatni kontakt')),
                ('next_action', models.CharField(blank=True, max_length=255, verbose_name='następne działanie')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='termin następnego działania')),
                ('lost_reason', models.CharField(blank=True, max_length=255, verbose_name='powód odrzucenia')),
                ('notes', models.TextField(blank=True, verbose_name='warunki i uwagi')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='distribution.bookingcampaign', verbose_name='kampania')),
                ('cinema', models.ForeignKey(limit_choices_to={'counterparty_type__in': ['cinema', 'cinema_chain']}, on_delete=django.db.models.deletion.PROTECT, related_name='booking_deals', to='distribution.counterparty', verbose_name='kino / sieć')),
                ('language_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_deals', to='distribution.languageversion', verbose_name='wersja językowa')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_deals', to=settings.AUTH_USER_MODEL, verbose_name='booker')),
            ],
            options={
                'verbose_name': 'negocjacja bookingowa',
                'verbose_name_plural': 'negocjacje bookingowe',
                'ordering': ['campaign__release_date', 'cinema__name'],
            },
        ),
        migrations.CreateModel(
            name='BookingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('call', 'Telefon'), ('email', 'E-mail'), ('meeting', 'Spotkanie'), ('note', 'Notatka'), ('task', 'Zadanie'), ('status', 'Zmiana statusu')], default='note', max_length=24, verbose_name='rodzaj')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='data i czas')),
                ('summary', models.TextField(verbose_name='notatka')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_activities', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='distribution.bookingdeal', verbose_name='negocjacja')),
            ],
            options={
                'verbose_name': 'aktywność bookingowa',
                'verbose_name_plural': 'aktywności bookingowe',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cinemabooking',
            name='crm_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='distribution.bookingdeal', verbose_name='negocjacja Booking CRM'),
        ),
        migrations.CreateModel(
            name='CinemaContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='imię i nazwisko')),
                ('role', models.CharField(blank=True, max_length=160, verbose_name='stanowisko / rola')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=80, verbose_name='telefon')),
                ('is_primary', models.BooleanField(default=False, verbose_name='kontakt główny')),
                ('active', models.BooleanField(default=True, verbose_name='aktywny')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('cinema', models.ForeignKey(limit_choices_to={'counterparty_type__in': ['cinema', 'cinema_chain']}, on_delete=django.db.models.deletion.CASCADE, related_name='cinema_contacts', to='distribution.counterparty', verbose_name='kino / sieć')),
            ],
            options={
                'verbose_name': 'kontakt bookingowy',
                'verbose_name_plural': 'kontakty bookingowe',
                'ordering': ['cinema__name', '-is_primary', 'name'],
            },
        ),
        migrations.AddField(
            model_name='bookingdeal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_deals', to='distribution.cinemacontact', verbose_name='osoba kontaktowa'),
        ),
        migrations.CreateModel(
            name='CinemaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='miasto')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adres')),
                ('website', models.URLField(blank=True, verbose_name='strona WWW')),
                ('screens_count', models.PositiveIntegerField(default=0, verbose_name='liczba sal')),
                ('seats_count', models.PositiveIntegerField(default=0, verbose_name='liczba miejsc')),
                ('active', models.BooleanField(default=True, verbose_name='aktywne')),
                ('booking_notes', models.TextField(blank=True, verbose_name='uwagi bookingowe')),
                ('chain', models.ForeignKey(blank=True, limit_choices_to={'counterparty_type': 'cinema_chain'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_venues', to='distribution.counterparty', verbose_name='sieć kin')),
                ('counterparty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_profile', to='distribution.counterparty', verbose_name='kino / sieć')),
            ],
            options={
                'verbose_name': 'profil kina / sieci',
                'verbose_name_plural': 'profile kin / sieci',
                'ordering': ['counterparty__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='bookingcampaign',
            constraint=models.UniqueConstraint(fields=('title', 'name'), name='unique_booking_campaign_name_per_title'),
        ),
        migrations.AddIndex(
            model_name='bookingdeal',
            index=models.Index(fields=['campaign', 'stage'], name='distributio_campaig_5de095_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingdeal',
            index=models.Index(fields=['owner', 'next_action_date'], name='distributio_owner_i_da80d2_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingdeal',
            constraint=models.UniqueConstraint(fields=('campaign', 'cinema'), name='unique_booking_deal_per_campaign_cinema'),
        ),
    ]
