# Generated by Django 5.2.16 on 2026-07-21 16:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _money(value):
    return Decimal(value or 0).quantize(Decimal('0.01'))


def migrate_existing_bookings(apps, schema_editor):
    BookingDeal = apps.get_model('distribution', 'BookingDeal')
    BookingTerm = apps.get_model('distribution', 'BookingTerm')
    CinemaBooking = apps.get_model('distribution', 'CinemaBooking')
    CinemaBookingWeek = apps.get_model('distribution', 'CinemaBookingWeek')
    BookingWeekSettlement = apps.get_model('distribution', 'BookingWeekSettlement')
    CinemaReportImportRow = apps.get_model('distribution', 'CinemaReportImportRow')
    SalesReport = apps.get_model('distribution', 'SalesReport')

    legacy_stages = dict(BookingDeal.objects.values_list('pk', 'stage'))
    for deal in BookingDeal.objects.all().iterator():
        old_basis = deal.settlement_basis
        if old_basis == 'fixed':
            deal.calculation_method = 'fixed_booking'
            deal.settlement_basis = 'gross_vat'
        elif old_basis == 'custom':
            deal.calculation_method = 'custom'
            deal.settlement_basis = 'gross_vat'
        elif deal.minimum_guarantee:
            deal.calculation_method = 'percentage_minimum'
        else:
            deal.calculation_method = 'percentage'
        if deal.stage in {'playing', 'holdover', 'ended'}:
            deal.stage = 'confirmed'
        deal.save(update_fields=['calculation_method', 'settlement_basis', 'stage'])
        BookingTerm.objects.get_or_create(
            deal_id=deal.pk,
            week_from=1,
            defaults={
                'name': 'Warunki podstawowe',
                'calculation_method': deal.calculation_method,
                'settlement_basis': deal.settlement_basis,
                'ticket_vat_rate': deal.ticket_vat_rate,
                'distributor_share_percent': deal.distributor_share_percent,
                'minimum_amount': deal.minimum_guarantee,
                'fixed_amount': deal.fixed_fee,
                'currency': deal.currency,
            },
        )

    for booking in CinemaBooking.objects.select_related('crm_deal').all().iterator():
        deal = booking.crm_deal
        legacy_stage = legacy_stages.get(booking.crm_deal_id)
        has_results = bool(booking.screenings or booking.admissions or booking.box_office_gross)
        if legacy_stage == 'ended':
            booking.status = 'ended'
        elif has_results or legacy_stage in {'playing', 'holdover'}:
            booking.status = 'playing'
        else:
            booking.status = 'scheduled'
        booking.currency = deal.currency if deal else 'PLN'
        booking.save(update_fields=['status', 'currency'])

        week_number = booking.exploitation_week or 1
        week, _ = CinemaBookingWeek.objects.get_or_create(
            booking_id=booking.pk,
            week_number=week_number,
            defaults={
                'date_from': booking.date_from,
                'date_to': booking.date_to,
                'planned_screens': deal.confirmed_screens if deal else 0,
                'screenings': booking.screenings,
                'admissions': booking.admissions,
                'box_office_gross': booking.box_office_gross,
                'currency': booking.currency,
                'status': 'reported' if has_results else 'planned',
                'source_reference': booking.source_reference,
            },
        )

        if deal:
            term = BookingTerm.objects.filter(deal_id=deal.pk, week_from__lte=week_number).order_by('-week_from').first()
            method = term.calculation_method
            basis = term.settlement_basis
            vat_rate = Decimal(term.ticket_vat_rate)
            share = Decimal(term.distributor_share_percent)
            minimum = _money(term.minimum_amount)
            fixed = _money(term.fixed_amount)
            term_id = term.pk
        else:
            method = 'percentage'
            basis = 'gross_vat'
            vat_rate = Decimal('8.00')
            share = Decimal(booking.distributor_share_percent)
            minimum = Decimal('0.00')
            fixed = Decimal('0.00')
            term_id = None

        gross = _money(booking.box_office_gross)
        net = _money(gross / (Decimal('1.00') + vat_rate / Decimal('100.00')))
        vat_amount = _money(gross - net)
        base = net if basis == 'net_vat' else gross
        percentage = _money(base * share / Decimal('100.00'))
        if method == 'percentage_minimum':
            rental = max(percentage, minimum)
        elif method == 'fixed_screening':
            rental = _money(fixed * booking.screenings)
        elif method in {'fixed_week', 'fixed_booking', 'custom'}:
            rental = fixed
        else:
            rental = percentage

        BookingWeekSettlement.objects.update_or_create(
            booking_week_id=week.pk,
            defaults={
                'term_id': term_id,
                'status': 'calculated',
                'calculation_method': method,
                'settlement_basis': basis,
                'ticket_vat_amount': vat_amount,
                'box_office_net_vat': net,
                'settlement_base': base,
                'percentage_amount': percentage,
                'minimum_amount': minimum,
                'fixed_amount': fixed,
                'adjustment_amount': Decimal('0.00'),
                'rental_amount': rental,
                'currency': booking.currency,
                'calculation_snapshot': {
                    'migrated_from_booking_id': booking.pk,
                    'box_office_gross_vat': str(gross),
                    'box_office_net_vat': str(net),
                    'settlement_base': str(base),
                    'share_percent': str(share),
                    'rental_amount': str(rental),
                },
            },
        )

        import_rows = CinemaReportImportRow.objects.filter(booking_id=booking.pk)
        import_rows.update(booking_week_id=week.pk)
        references = {booking.source_reference, f'cinema-booking-{booking.pk}'}
        references.update(f'cinema-import-row-{row_id}' for row_id in import_rows.values_list('pk', flat=True))
        references.discard('')
        existing_reports = list(SalesReport.objects.filter(source_reference__in=references).order_by('pk'))
        canonical_reference = f'cinema-booking-week-{week.pk}'
        report_defaults = {
            'title_id': booking.title_id,
            'counterparty_id': booking.cinema_id,
            'sales_agreement_id': None,
            'exploitation_field': 'cinema',
            'territory_id': None,
            'period_start': week.date_from,
            'period_end': week.date_to,
            'currency': booking.currency,
            'gross_revenue': rental,
            'deductions': Decimal('0.00'),
            'vat_withholding': Decimal('0.00'),
            'status': 'imported',
            'notes': (
                f'Zmigrowano do tygodniowego rozliczenia bookingu #{booking.pk}. '
                f'Box office brutto (VAT): {gross} {booking.currency}; '
                f'należność dystrybutora: {rental} {booking.currency}.'
            ),
        }
        if existing_reports:
            primary = existing_reports[0]
            for field_name, value in report_defaults.items():
                setattr(primary, field_name, value)
            primary.source_reference = canonical_reference
            primary.save()
            for duplicate in existing_reports[1:]:
                duplicate.status = 'rejected'
                duplicate.notes = f'Zastąpiony przez {canonical_reference}. {duplicate.notes}'.strip()
                duplicate.save(update_fields=['status', 'notes'])
        elif has_results:
            SalesReport.objects.create(
                source_reference=canonical_reference,
                source_file=booking.source_file,
                **report_defaults,
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0021_alter_counterparty_reporting_cycle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcampaign',
            name='default_calculation_method',
            field=models.CharField(choices=[('percentage', 'Procent od box office'), ('percentage_minimum', 'Procent, nie mniej niż minimum'), ('fixed_screening', 'Stawka za seans'), ('fixed_week', 'Stawka za tydzień'), ('fixed_booking', 'Stawka za cały booking'), ('custom', 'Kwota ustalona indywidualnie')], default='percentage', max_length=32, verbose_name='domyślny sposób rozliczenia'),
        ),
        migrations.AddField(
            model_name='bookingcampaign',
            name='default_fixed_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='domyślna stawka stała'),
        ),
        migrations.AddField(
            model_name='bookingcampaign',
            name='default_minimum_guarantee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='domyślne minimum / MG kina'),
        ),
        migrations.AddField(
            model_name='bookingcampaign',
            name='default_settlement_basis',
            field=models.CharField(choices=[('gross_vat', 'Box office brutto (sprzedaż biletów z VAT)'), ('net_vat', 'Box office netto (po odjęciu VAT)')], default='gross_vat', max_length=24, verbose_name='domyślna podstawa rozliczenia'),
        ),
        migrations.AddField(
            model_name='bookingcampaign',
            name='default_ticket_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='domyślna stawka VAT biletów (%)'),
        ),
        migrations.AddField(
            model_name='bookingdeal',
            name='calculation_method',
            field=models.CharField(choices=[('percentage', 'Procent od box office'), ('percentage_minimum', 'Procent, nie mniej niż minimum'), ('fixed_screening', 'Stawka za seans'), ('fixed_week', 'Stawka za tydzień'), ('fixed_booking', 'Stawka za cały booking'), ('custom', 'Kwota ustalona indywidualnie')], default='percentage', max_length=32, verbose_name='sposób rozliczenia'),
        ),
        migrations.AddField(
            model_name='bookingdeal',
            name='ticket_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='stawka VAT biletów (%)'),
        ),
        migrations.AddField(
            model_name='cinemabooking',
            name='currency',
            field=models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta'),
        ),
        migrations.AddField(
            model_name='cinemabooking',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Zaplanowany'), ('playing', 'Gra'), ('ended', 'Zakończony'), ('cancelled', 'Anulowany')], default='scheduled', max_length=20, verbose_name='status eksploatacji'),
        ),
        migrations.AddField(
            model_name='cinemareportimport',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='SHA-256 pliku'),
        ),
        migrations.AddField(
            model_name='cinemareportimportrow',
            name='source_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='odcisk wiersza źródłowego'),
        ),
        migrations.AlterField(
            model_name='bookingdeal',
            name='settlement_basis',
            field=models.CharField(choices=[('gross_vat', 'Box office brutto (sprzedaż biletów z VAT)'), ('net_vat', 'Box office netto (po odjęciu VAT)')], default='gross_vat', max_length=24, verbose_name='podstawa rozliczenia'),
        ),
        migrations.AlterField(
            model_name='bookingdeal',
            name='stage',
            field=models.CharField(choices=[('target', 'Do kontaktu'), ('contacted', 'Kontakt wykonany'), ('offer', 'Oferta'), ('negotiation', 'Negocjacje'), ('confirmed', 'Potwierdzony'), ('lost', 'Odrzucony')], default='target', max_length=24, verbose_name='etap'),
        ),
        migrations.CreateModel(
            name='BookingTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Warunki podstawowe', max_length=120, verbose_name='nazwa warunków')),
                ('week_from', models.PositiveIntegerField(default=1, help_text='Warunki obowiązują do początku kolejnego wpisu w harmonogramie.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='obowiązuje od tygodnia')),
                ('calculation_method', models.CharField(choices=[('percentage', 'Procent od box office'), ('percentage_minimum', 'Procent, nie mniej niż minimum'), ('fixed_screening', 'Stawka za seans'), ('fixed_week', 'Stawka za tydzień'), ('fixed_booking', 'Stawka za cały booking'), ('custom', 'Kwota ustalona indywidualnie')], default='percentage', max_length=32, verbose_name='sposób rozliczenia')),
                ('settlement_basis', models.CharField(choices=[('gross_vat', 'Box office brutto (sprzedaż biletów z VAT)'), ('net_vat', 'Box office netto (po odjęciu VAT)')], default='gross_vat', max_length=24, verbose_name='podstawa rozliczenia')),
                ('ticket_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='stawka VAT biletów (%)')),
                ('distributor_share_percent', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='udział dystrybutora (%)')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='minimum / MG kina')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='stawka stała')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='uwagi')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='distribution.bookingdeal', verbose_name='negocjacja')),
            ],
            options={
                'verbose_name': 'warunki bookingu',
                'verbose_name_plural': 'harmonogram warunków bookingu',
                'ordering': ['deal', 'week_from'],
            },
        ),
        migrations.CreateModel(
            name='CinemaBookingWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='tydzień grania')),
                ('date_from', models.DateField(verbose_name='data od')),
                ('date_to', models.DateField(verbose_name='data do')),
                ('planned_screens', models.PositiveIntegerField(default=0, verbose_name='planowane ekrany')),
                ('screenings', models.PositiveIntegerField(default=0, verbose_name='liczba seansów')),
                ('admissions', models.PositiveIntegerField(default=0, verbose_name='widzowie')),
                ('box_office_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='box office brutto (VAT)')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta')),
                ('status', models.CharField(choices=[('planned', 'Oczekuje na raport'), ('reported', 'Raport wczytany'), ('verified', 'Zweryfikowany'), ('locked', 'Zamknięty'), ('corrected', 'Po korekcie')], default='planned', max_length=20, verbose_name='status raportu tygodniowego')),
                ('decision', models.CharField(choices=[('pending', 'Do decyzji'), ('extend', 'Przedłużyć'), ('renegotiate', 'Zmienić warunki'), ('end', 'Zakończyć')], default='pending', max_length=20, verbose_name='decyzja na kolejny tydzień')),
                ('source_reference', models.CharField(blank=True, max_length=255, verbose_name='referencja źródła')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='distribution.cinemabooking', verbose_name='booking')),
            ],
            options={
                'verbose_name': 'tydzień bookingu kinowego',
                'verbose_name_plural': 'tygodnie bookingów kinowych',
                'ordering': ['booking', 'week_number'],
            },
        ),
        migrations.CreateModel(
            name='BookingWeekSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Robocze'), ('calculated', 'Obliczone'), ('approved', 'Zatwierdzone'), ('void', 'Anulowane')], default='draft', max_length=20, verbose_name='status')),
                ('calculation_method', models.CharField(choices=[('percentage', 'Procent od box office'), ('percentage_minimum', 'Procent, nie mniej niż minimum'), ('fixed_screening', 'Stawka za seans'), ('fixed_week', 'Stawka za tydzień'), ('fixed_booking', 'Stawka za cały booking'), ('custom', 'Kwota ustalona indywidualnie')], max_length=32, verbose_name='sposób rozliczenia')),
                ('settlement_basis', models.CharField(choices=[('gross_vat', 'Box office brutto (sprzedaż biletów z VAT)'), ('net_vat', 'Box office netto (po odjęciu VAT)')], max_length=24, verbose_name='podstawa rozliczenia')),
                ('ticket_vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='VAT w sprzedaży biletów')),
                ('box_office_net_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='box office netto (VAT)')),
                ('settlement_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='podstawa naliczenia')),
                ('percentage_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='kwota procentowa')),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='minimum')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='stawka stała')),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='korekta')),
                ('rental_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='należność dystrybutora')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta')),
                ('calculation_snapshot', models.JSONField(blank=True, default=dict, verbose_name='zapis kalkulacji')),
                ('calculated_at', models.DateTimeField(blank=True, null=True, verbose_name='obliczono')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='zatwierdzono')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_booking_settlements', to=settings.AUTH_USER_MODEL, verbose_name='zatwierdził')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements', to='distribution.bookingterm', verbose_name='zastosowane warunki')),
                ('booking_week', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='distribution.cinemabookingweek', verbose_name='tydzień bookingu')),
            ],
            options={
                'verbose_name': 'rozliczenie tygodnia bookingu',
                'verbose_name_plural': 'rozliczenia tygodni bookingów',
                'ordering': ['-booking_week__date_from'],
            },
        ),
        migrations.AddField(
            model_name='cinemareportimportrow',
            name='booking_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='distribution.cinemabookingweek', verbose_name='utworzony tydzień bookingu'),
        ),
        migrations.CreateModel(
            name='CinemaBookingWeekRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_data', models.JSONField(default=dict, verbose_name='dane przed korektą')),
                ('incoming_data', models.JSONField(default=dict, verbose_name='dane po korekcie')),
                ('reason', models.CharField(default='Korekta raportu kina', max_length=255, verbose_name='powód')),
                ('source_reference', models.CharField(blank=True, max_length=255, verbose_name='referencja źródła')),
                ('booking_week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='distribution.cinemabookingweek', verbose_name='tydzień bookingu')),
            ],
            options={
                'verbose_name': 'korekta tygodnia bookingu',
                'verbose_name_plural': 'historia korekt tygodni bookingów',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bookingterm',
            constraint=models.UniqueConstraint(fields=('deal', 'week_from'), name='unique_booking_term_start_week'),
        ),
        migrations.AddIndex(
            model_name='cinemabookingweek',
            index=models.Index(fields=['status', 'date_to'], name='distributio_status_e3c3bf_idx'),
        ),
        migrations.AddIndex(
            model_name='cinemabookingweek',
            index=models.Index(fields=['booking', 'date_from', 'date_to'], name='distributio_booking_46d548_idx'),
        ),
        migrations.AddConstraint(
            model_name='cinemabookingweek',
            constraint=models.UniqueConstraint(fields=('booking', 'week_number'), name='unique_cinema_booking_week'),
        ),
        migrations.RunPython(migrate_existing_bookings, noop_reverse),
    ]
