# Generated by Django 5.2.16 on 2026-07-28 16:02

import django.db.models.deletion
from django.db import migrations, models


def lock_existing_revenue_weeks(apps, schema_editor):
    BookingWeekSettlement = apps.get_model("distribution", "BookingWeekSettlement")
    CinemaBookingWeek = apps.get_model("distribution", "CinemaBookingWeek")
    SalesReport = apps.get_model("distribution", "SalesReport")

    for settlement in BookingWeekSettlement.objects.all().iterator():
        source_reference = f"cinema-booking-week-{settlement.booking_week_id}"
        if not SalesReport.objects.filter(source_reference=source_reference).exists():
            continue
        CinemaBookingWeek.objects.filter(pk=settlement.booking_week_id).update(status="locked")
        BookingWeekSettlement.objects.filter(pk=settlement.pk).update(
            status="approved",
            approved_at=settlement.calculated_at or settlement.updated_at,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0022_bookingcampaign_default_calculation_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingweeksettlement',
            name='invoice_file',
            field=models.FileField(blank=True, upload_to='booking_invoices/', verbose_name='faktura sprzedaży'),
        ),
        migrations.AddField(
            model_name='bookingweeksettlement',
            name='invoice_issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='data wystawienia faktury'),
        ),
        migrations.AddField(
            model_name='bookingweeksettlement',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=120, verbose_name='numer faktury'),
        ),
        migrations.AddField(
            model_name='bookingweeksettlement',
            name='paid_at',
            field=models.DateField(blank=True, null=True, verbose_name='data płatności'),
        ),
        migrations.AddField(
            model_name='bookingweeksettlement',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='termin płatności'),
        ),
        migrations.AddField(
            model_name='bookingweeksettlement',
            name='payment_notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='uwagi do płatności'),
        ),
        migrations.AddField(
            model_name='cinemareportimport',
            name='target_booking_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_report_imports', to='distribution.cinemabookingweek', verbose_name='docelowy tydzień bookingu'),
        ),
        migrations.AddField(
            model_name='cinemareportimportrow',
            name='reported_rental_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='należność dystrybutora wg raportu kina'),
        ),
        migrations.RunPython(lock_existing_revenue_weeks, migrations.RunPython.noop),
    ]
