# Generated by Django 5.2.16 on 2026-08-03 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0023_bookingweeksettlement_invoice_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cinemareportimportrow',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('duplicate', 'duplikat'), ('summary_row', 'wiersz sumy / podsumowania'), ('not_our_title', 'nie dotyczy naszego tytułu'), ('wrong_period', 'nieprawidłowy okres'), ('invalid_data', 'błędne dane źródłowe'), ('other', 'inny powód')], max_length=30, verbose_name='powód odrzucenia'),
        ),
        migrations.AddField(
            model_name='cinemareportimportrow',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data weryfikacji'),
        ),
        migrations.AddField(
            model_name='cinemareportimportrow',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cinema_report_rows', to=settings.AUTH_USER_MODEL, verbose_name='zweryfikował'),
        ),
    ]
