# Generated by Django 5.2.16 on 2026-08-05 13:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0024_cinemareportimportrow_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PABudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Budżet P&A', max_length=160, verbose_name='nazwa budżetu')),
                ('currency', models.CharField(choices=[('PLN', 'PLN'), ('EUR', 'EURO'), ('USD', 'US$')], default='PLN', max_length=3, verbose_name='waluta')),
                ('status', models.CharField(choices=[('draft', 'roboczy'), ('approved', 'zatwierdzony'), ('closed', 'zamknięty')], default='draft', max_length=20, verbose_name='status')),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='okres od')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='okres do')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pa_budgets', to='distribution.title', verbose_name='tytuł')),
            ],
            options={
                'verbose_name': 'budżet P&A',
                'verbose_name_plural': 'budżety P&A',
                'ordering': ['title__title_pl', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PABudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180, verbose_name='pozycja budżetu')),
                ('category', models.CharField(choices=[('pa', 'P&A'), ('digital_marketing', 'digital marketing'), ('pr', 'PR'), ('key_art', 'plakat / key art'), ('trailer', 'trailer'), ('dcp', 'DCP'), ('kdm', 'KDM'), ('subtitles', 'napisy'), ('dubbing', 'dubbing / lektor'), ('qc', 'QC'), ('delivery', 'delivery'), ('festivals', 'festiwale'), ('promo_materials', 'materiały promocyjne'), ('sales_commission', 'prowizje sprzedażowe'), ('legal', 'koszty prawne'), ('other', 'inne')], default='pa', max_length=40, verbose_name='kategoria')),
                ('planned_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='plan Netto (VAT)')),
                ('recoupable', models.BooleanField(default=True, verbose_name='do odzyskania (recoupable)')),
                ('scope_mode', models.CharField(choices=[('all', 'Wszystkie pola'), ('selected', 'Wybrane pola'), ('allocated', 'Podział procentowy')], default='all', max_length=20, verbose_name='zakres kosztu')),
                ('scope_fields', models.JSONField(blank=True, default=list, verbose_name='wybrane pola eksploatacji')),
                ('allocation_percentages', models.JSONField(blank=True, default=dict, verbose_name='podział procentowy na pola')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='kolejność')),
                ('notes', models.TextField(blank=True, verbose_name='uwagi')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='distribution.pabudget', verbose_name='budżet P&A')),
            ],
            options={
                'verbose_name': 'pozycja budżetu P&A',
                'verbose_name_plural': 'pozycje budżetu P&A',
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cost',
            name='budget_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='distribution.pabudgetline', verbose_name='pozycja budżetu P&A'),
        ),
        migrations.AddConstraint(
            model_name='pabudgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'name'), name='unique_pa_budget_line_name'),
        ),
    ]
