# Generated by Django 5.2.16 on 2026-08-06 09:56

from django.db import migrations, models


def flag_numeric_counterparty_names(apps, schema_editor):
    from decimal import Decimal, InvalidOperation

    Counterparty = apps.get_model("distribution", "Counterparty")
    note = "Nazwa wygląda jak wartość liczbowa przeniesiona z innej kolumny importu."
    for counterparty in Counterparty.objects.only("pk", "name").iterator():
        candidate = str(counterparty.name or "").strip().replace(" ", "").replace(",", ".")
        try:
            Decimal(candidate)
        except (InvalidOperation, ValueError):
            continue
        Counterparty.objects.filter(pk=counterparty.pk).update(
            name_review_required=True,
            name_review_note=note,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0025_pabudget_pabudgetline_cost_budget_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counterparty',
            name='name_review_note',
            field=models.CharField(blank=True, max_length=255, verbose_name='powód weryfikacji nazwy'),
        ),
        migrations.AddField(
            model_name='counterparty',
            name='name_review_required',
            field=models.BooleanField(default=False, verbose_name='nazwa wymaga weryfikacji'),
        ),
        migrations.RunPython(flag_numeric_counterparty_names, migrations.RunPython.noop),
    ]
