# Generated by Django 5.2.16 on 2026-08-06 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0026_counterparty_name_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisitionagreement',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='distribution.acquisitionagreement', verbose_name='poprzednia wersja'),
        ),
        migrations.AddField(
            model_name='acquisitionagreement',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='wersja'),
        ),
        migrations.AddField(
            model_name='royaltystatement',
            name='correction_reason',
            field=models.TextField(blank=True, verbose_name='powód korekty'),
        ),
        migrations.AddField(
            model_name='royaltystatement',
            name='revision',
            field=models.PositiveIntegerField(default=1, verbose_name='rewizja'),
        ),
        migrations.AddField(
            model_name='royaltystatement',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='distribution.royaltystatement', verbose_name='korygowany statement'),
        ),
        migrations.AddField(
            model_name='royaltystatement',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data anulowania'),
        ),
        migrations.AddField(
            model_name='royaltystatement',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_royalty_statements', to=settings.AUTH_USER_MODEL, verbose_name='anulował'),
        ),
        migrations.AddField(
            model_name='waterfallplan',
            name='source_agreement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waterfall_plans', to='distribution.acquisitionagreement', verbose_name='źródłowa umowa'),
        ),
        migrations.AlterField(
            model_name='royaltystatement',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('sent', 'wysłany'), ('approved', 'zaakceptowany'), ('paid', 'opłacony'), ('disputed', 'sporny'), ('voided', 'anulowany / zastąpiony')], default='draft', max_length=30, verbose_name='status'),
        ),
    ]
