from django.urls import path

from .booking_views import (
    booking_campaign_form,
    booking_bulk_cinemas,
    booking_cinema_form,
    booking_crm,
    booking_deal_form,
    booking_week_update,
    booking_week_report,
)
from .views import (
    avails,
    contract_waterfall_wizard,
    dashboard,
    document_center,
    document_review,
    pa_budget_setup,
    reports,
    reports_export_csv,
    session_keepalive,
    settlement_workbench,
    statement_center,
    title_catalog_export,
    title_detail,
    title_list,
    title_setup,
    web_app_manifest,
)

app_name = "distribution"

urlpatterns = [
    path("manifest.webmanifest", web_app_manifest, name="web_app_manifest"),
    path("", dashboard, name="dashboard"),
    path("session/keepalive/", session_keepalive, name="session_keepalive"),
    path("titles/", title_list, name="title_list"),
    path("titles/new/", title_setup, name="title_create"),
    path("titles/<int:pk>/", title_detail, name="title_detail"),
    path("titles/<int:pk>/edit/", title_setup, name="title_edit"),
    path("titles/<int:title_pk>/pa-budget/new/", pa_budget_setup, name="pa_budget_create"),
    path("titles/<int:title_pk>/pa-budget/<int:pk>/", pa_budget_setup, name="pa_budget_edit"),
    path("booking/", booking_crm, name="booking_crm"),
    path("booking/campaigns/new/", booking_campaign_form, name="booking_campaign_create"),
    path("booking/campaigns/<int:pk>/", booking_campaign_form, name="booking_campaign_edit"),
    path("booking/cinemas/add-to-campaign/", booking_bulk_cinemas, name="booking_bulk_cinemas"),
    path("booking/deals/new/", booking_deal_form, name="booking_deal_create"),
    path("booking/deals/<int:pk>/", booking_deal_form, name="booking_deal_edit"),
    path("booking/weeks/<int:pk>/update/", booking_week_update, name="booking_week_update"),
    path("booking/weeks/<int:pk>/report/", booking_week_report, name="booking_week_report"),
    path("booking/cinemas/new/", booking_cinema_form, name="booking_cinema_create"),
    path("booking/cinemas/<int:pk>/", booking_cinema_form, name="booking_cinema_edit"),
    path("contracts/setup/", contract_waterfall_wizard, name="contract_waterfall_wizard"),
    path("avails/", avails, name="avails"),
    path("documents/", document_center, name="document_center"),
    path("documents/<int:pk>/", document_review, name="document_review"),
    path("settlements/", settlement_workbench, name="settlement_workbench"),
    path("statements/", statement_center, name="statement_center"),
    path("reports/", reports, name="reports"),
    path("reports/export/", reports_export_csv, name="reports_export_csv"),
    path("reports/export-360/", title_catalog_export, name="title_catalog_export"),
]
